#!/usr/bin/env python3
"""Render the Azure variables for the platform's .env file.

Reads `terraform output -json` and writes a .env.azure fragment containing the
six Azure-dependent variables from .env.example.

The IoT Hub SAS token is computed here rather than in Terraform: Terraform has
no HMAC-SHA256 function, and the azurerm provider exposes only the shared access
policy key, not a token. Because IoT Hub SAS tokens expire (see
docs/prerequisites/iot-hub.md), this script can be re-run on its own to mint a
fresh token without touching Azure or Terraform state.

Uses only the standard library -- no pip installs, no `az iot` extension.
"""

import argparse
import base64
import hashlib
import hmac
import json
import os
import subprocess
import sys
import time
import urllib.parse
from pathlib import Path

TERRAFORM_DIR = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = TERRAFORM_DIR.parent / ".env.azure"


def terraform_outputs(tf_dir: Path) -> dict:
    """Return the Terraform outputs as {name: value}."""
    try:
        proc = subprocess.run(
            ["terraform", f"-chdir={tf_dir}", "output", "-json"],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("error: terraform not found on PATH")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: terraform output failed:\n{exc.stderr.strip()}")

    raw = json.loads(proc.stdout)
    if not raw:
        sys.exit("error: no Terraform outputs found -- run `terraform apply` first")
    return {key: item["value"] for key, item in raw.items()}


def iot_hub_sas_token(hostname: str, policy_name: str, key: str, ttl_seconds: int) -> str:
    """Build an IoT Hub SAS token.

    Signature is HMAC-SHA256 over "<url-encoded resource>\\n<expiry>", keyed with
    the base64-decoded policy key, per the Azure IoT Hub security token format.
    """
    resource = urllib.parse.quote(hostname, safe="")
    expiry = int(time.time()) + ttl_seconds
    to_sign = f"{resource}\n{expiry}".encode("utf-8")

    try:
        secret = base64.b64decode(key)
    except Exception:
        sys.exit("error: iot_policy_primary_key is not valid base64")

    signature = base64.b64encode(hmac.new(secret, to_sign, hashlib.sha256).digest())
    encoded_signature = urllib.parse.quote(signature.decode("utf-8"), safe="")

    return (
        f"SharedAccessSignature sr={resource}"
        f"&sig={encoded_signature}"
        f"&se={expiry}"
        f"&skn={policy_name}"
    )


def render(values: dict) -> str:
    lines = [
        "# Generated by terraform/scripts/gen-env.py -- do not commit.",
        "# Copy these values into your .env file.",
        "#",
        "# SAS_TOKEN expires; re-run the script to mint a fresh one.",
        "",
    ]
    lines += [f"{key}='{value}'" for key, value in values.items()]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ttl-days",
        type=int,
        default=30,
        help="validity of the generated IoT Hub SAS token (default: 30)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"file to write (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="print to stdout instead of writing a file",
    )
    parser.add_argument(
        "--chdir",
        type=Path,
        default=TERRAFORM_DIR,
        help="Terraform working directory",
    )
    args = parser.parse_args()

    if args.ttl_days <= 0:
        sys.exit("error: --ttl-days must be positive")

    out = terraform_outputs(args.chdir)

    missing = [
        name
        for name in (
            "iot_hub_name",
            "iot_policy_name",
            "iot_policy_primary_key",
            "public_storage_account_name",
            "internal_storage_account_name",
            "blob_sas_token_platform_config",
            "blob_sas_token_module_conf",
        )
        if not out.get(name)
    ]
    if missing:
        sys.exit(f"error: missing Terraform outputs: {', '.join(missing)}")

    values = {
        "IOT_HUB_NAME": out["iot_hub_name"],
        "SAS_TOKEN": iot_hub_sas_token(
            hostname=out["iot_hub_name"],
            policy_name=out["iot_policy_name"],
            key=out["iot_policy_primary_key"],
            ttl_seconds=args.ttl_days * 86400,
        ),
        "PUBLIC_STORAGE_ACCOUNT_NAME": out["public_storage_account_name"],
        "INTERNAL_STORAGE_ACCOUNT_NAME": out["internal_storage_account_name"],
        "BLOB_SAS_TOKEN_PLATFORM_CONFIG": out["blob_sas_token_platform_config"],
        "BLOB_SAS_TOKEN_MODULE_CONF": out["blob_sas_token_module_conf"],
    }

    content = render(values)

    if args.stdout:
        sys.stdout.write(content)
        return

    # Written 0600: the file holds credentials.
    fd = os.open(args.output, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as handle:
        handle.write(content)

    print(f"Wrote {args.output}")
    print(f"IoT Hub SAS token valid for {args.ttl_days} day(s).")
    print("Copy the values into .env, then: docker compose up --pull always")


if __name__ == "__main__":
    main()
